### PR TITLE
query: fix bug when first adding a resource which matches a filter

### PR DESCRIPTION
**Pull request by andrewbonney**
Fixes an uncaught exception relating to WebSocket subscriptions when a freshly registered resource is added.

### CODE REVIEW

**Comment by andrewbonney** [comment]
Thanks for the quick review. I'll rename those variables as I agree they're terrible. The code snippet you mention is still required as it covers the case of both variables being None rather than just one of them.

**Comment by andrewbonney** [comment]
@dannymeloy could you give that a re-scan and see if it makes a little more sense?

**Comment by dannymeloy** [comment]
If it passes all the testing then LGTM, it reads alot better now.

**Comment by andrewbonney** [comment]
@dannymeloy sorry, I found more bugs. Could you have another scan once the tests have passed?

**Comment by dannymeloy** [comment]
I can't claim to know enough about sockets to check the `querysockets` commit but other than that looks good to me

**Pull request merged**
